### ISSUE TITLE
Image with Raspbian kernel and boot binaries

### ISSUE THREAD

**Issue by daniell1** [drtyhlpr/rpi2-gen-image#26]
Hi. Just for your informationen: I've created a fork that uses kernel and boot binaries from Raspbian here: https://github.com/daniell1/rpi2-gen-image

If you like, I can add it as an option to your image. Please note that this will mix Debian and Raspbian repositories and might end up in an unstable system. If you don't want me to add it, I'll try to maintain it separately.

**Comment by drtyhlpr** [comment]
Hi daniel1 thanks for the fix. I am not aware about the risks of using mixed bins and I need some time to try out. As long as this is an optional cmd line ARG I think this is a good idea.

I am also planning to add a custom cross kernel compile and optinal initramfs option. but well I am not sure if I should mabye plan a new version of this script (then) because with custom kernel this script would not be limited only to rpi2 anymore and support other arm9 socs/boards
